In [2]:
import numpy as np

In [8]:
arr_a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr_b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [9]:
arr_c = np.intersect1d(arr_a, arr_b)
arr_c

array([2, 4])

In [10]:
arr_d = np.setdiff1d(arr_a, arr_b)
arr_d

array([1, 3, 5, 6])

In [4]:
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_f = arr_e[np.where((arr_e > 4) & (arr_e < 11))]
arr_f

array([ 6,  9, 10,  8,  6])