In [4]:
import numpy as np

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
type(arr)

numpy.ndarray

In [10]:
arr.shape[0]

10

In [20]:
arr_odd = np.extract(np.mod(arr, 2) == 0, arr)
arr_odd

array([0, 2, 4, 6, 8])

In [23]:
arr_even = np.extract(np.mod(arr, 2) == 1, arr)
arr_even

array([11, 13, 15, 17, 19])

In [30]:
arr_update_1 = np.copy(arr)
arr_update_1[np.where(np.mod(arr, 2))] = 100
arr_update_1

array([ 10, 100,  12, 100,  14, 100,  16, 100,  18, 100])