# Ex1: Decomposition

## Câu 1: LU Decomposition
- Tạo ma trận A(4x4) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
- Phân tích thành các thành phần P, L, U. In kết quả
- Tại tạo ma trận B từ các thành phần P, L, U. 

## Câu 2: Hãy dùng LU Decompostion để làm lại bài toán này:
- Cho: <br/>
    2a + b  + c = 4<br/> 
     a + 3b + 2c = 5<br/>
     a          = 6<br/>   
- Quy về Ax = B. Sau đó giải tìm x
- Phân tích thành các thành phần P, L, U từ A. In kết quả
- Tại tạo ma trận A từ các thành phần P, L, U với tên là A_new

## Câu 3: QR Decomposition
- Tạo ma trận C(4x5) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
- Phân tích thành các thành phần Q, R. In kết quả
- Tái tạo ma trận D từ các thành phần Q, R. 

## Câu 4: Cholesky Decomposition
- Tạo ma trận E(3x3) vuông chứa các giá trị ngẫu nhiên trong khoảng 3 - 9.
- Từ đó chuyển E thành ma trận vuông đối xứng theo tam giác dưới dường chéo chính
- Kiểm tra nếu mọi thành phần đều không âm thì:
    - Phân tích thành L. In kết quả
    - Tái tạo ma trận F từ các thành phần L.L.T 
- Ngược lại thì thông báo E có thành phần âm
- Chú ý: dùng np.linalg.eigvalsh(E) để kiểm tra xem mọi thành phần có âm hay không
- Mở rộng: Thực hiện việc tạo ma trận vuông đối xứng với mọi thành phần đều không âm và phân tích.

## Câu 1: LU Decomposition (Gợi ý)

In [ ]:
from lib import *
import numpy
import scipy
from scipy.linalg import lu

In [2]:
A = create_matrix_random(4, 4, 1, 10)
A

array([[ 8, 10, 10,  3],
       [ 2,  9,  6,  9],
       [ 8,  2,  2,  8],
       [ 1,  1,  4,  1]])

In [3]:
P, L, U = lu(A)

In [4]:
P

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [5]:
L

array([[ 1.     ,  0.     ,  0.     ,  0.     ],
       [ 1.     ,  1.     ,  0.     ,  0.     ],
       [ 0.25   , -0.8125 ,  1.     ,  0.     ],
       [ 0.125  ,  0.03125, -1.     ,  1.     ]])

In [6]:
U

array([[ 8.     , 10.     , 10.     ,  3.     ],
       [ 0.     , -8.     , -8.     ,  5.     ],
       [ 0.     ,  0.     , -3.     , 12.3125 ],
       [ 0.     ,  0.     ,  0.     , 12.78125]])

In [7]:
B = P.dot(L).dot(U)
B

array([[ 8., 10., 10.,  3.],
       [ 2.,  9.,  6.,  9.],
       [ 8.,  2.,  2.,  8.],
       [ 1.,  1.,  4.,  1.]])

## Câu 2: Hãy dùng LU Decompostion để làm lại bài toán này:
- Cho: <br/>
    2a + b  + c = 4<br/> 
     a + 3b + 2c = 5<br/>
     a          = 6<br/>   
- Quy về Ax = B. Sau đó giải tìm x
- Phân tích thành các thành phần P, L, U từ A. In kết quả
- Tại tạo ma trận A từ các thành phần P, L, U với tên là A_new

In [8]:
import scipy.linalg as linalg 

In [9]:
# define matrix A using Numpy arrays 
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 

In [10]:
# define matrix B 
B = np.array([4, 5, 6]) 

In [11]:
# With LU = A
LU = linalg.lu_factor(A)
LU

(array([[ 2. ,  1. ,  1. ],
        [ 0.5,  2.5,  1.5],
        [ 0.5, -0.2, -0.2]]),
 array([0, 1, 2], dtype=int32))

In [12]:
#solve given LU and B 
x = linalg.lu_solve(LU, B) 
print("Solutions(a, b, c):\n",x) 

Solutions(a, b, c):
 [  6.  15. -23.]


In [13]:
P, L, U = scipy.linalg.lu(A) 

In [14]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -0.2,  1. ]])

In [16]:
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  1.5],
       [ 0. ,  0. , -0.2]])

In [37]:
A_new = P.dot(L).dot(U)
# A_new
L.dot(U)

array([[5.65685425, 2.82842712, 2.82842712],
       [4.24264069, 6.79839208, 4.92756338],
       [4.24264069, 5.46208587, 3.74033001]])

## Câu 3: QR Decomposition (Gợi ý)
- Tạo ma trận C(4x5) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
- Phân tích thành các thành phần Q, R. In kết quả
- Tái tạo ma trận D từ các thành phần Q, R. 

In [38]:
from numpy.linalg import qr

In [39]:
B = create_matrix_random(4, 5, 5, 10)
B

array([[ 8, 11,  5,  5, 11],
       [ 8, 11,  6,  9, 10],
       [ 6, 11, 11,  7,  5],
       [ 7,  9,  6, 11, 11]])

In [40]:
Q, R = qr(B, 'complete')

In [41]:
Q

array([[-0.54815097, -0.16898057,  0.61183053,  0.5446462 ],
       [-0.54815097, -0.16898057,  0.17464724, -0.80029646],
       [-0.41111323,  0.89368076, -0.17097343,  0.05557614],
       [-0.4796321 , -0.37977077, -0.75228308,  0.24453503]])

In [42]:
R

array([[-14.59451952, -20.89825565, -13.42969871, -15.8278592 ,
        -18.84268952],
       [  0.        ,   2.69497881,   5.69307741,  -0.28744118,
         -3.2576667 ],
       [  0.        ,   0.        ,  -2.28737012,  -4.8409501 ,
         -0.65337283],
       [  0.        ,   0.        ,   0.        ,  -1.40051881,
          0.95590966]])

In [43]:
C = Q.dot(R)

In [44]:
C

array([[ 8., 11.,  5.,  5., 11.],
       [ 8., 11.,  6.,  9., 10.],
       [ 6., 11., 11.,  7.,  5.],
       [ 7.,  9.,  6., 11., 11.]])

## Câu 4: Cholesky Decomposition (Gợi ý)
- Tạo ma trận E(3x3) vuông chứa các giá trị ngẫu nhiên trong khoảng 3 - 9.
- Từ đó chuyển E thành ma trận vuông đối xứng theo tam giác dưới dường chéo chính
- Kiểm tra nếu mọi thành phần đều không âm thì:
    - Phân tích thành L. In kết quả
    - Tái tạo ma trận F từ các thành phần L.L.T 
- Ngược lại thì thông báo E có thành phần âm
- Chú ý: dùng np.linalg.eigvalsh(E) để kiểm tra xem mọi thành phần có âm hay không
- Mở rộng: Thực hiện việc tạo ma trận vuông đối xứng với mọi thành phần đều không âm và phân tích.

In [45]:
from numpy.linalg import cholesky

In [46]:
E = create_matrix_random(3, 3, 3, 9)
E

array([[ 7,  6,  5],
       [ 5,  7, 10],
       [ 3,  9, 10]])

In [47]:
E.shape

(3, 3)

In [48]:
for i in range(E.shape[0]):
    for j in range(i):
        E[j][i] = E[i][j]
E

array([[ 7,  5,  3],
       [ 5,  7,  9],
       [ 3,  9, 10]])

In [49]:
# Chú ý: Có 1 thành phần bị âm nên sẽ không tạo được L.
# Kiểm tra mọi thành phần đều dương thì tạo L

In [50]:
test = np.linalg.eigvalsh(E)
test

array([-1.16227766,  5.16227766, 20.        ])

In [52]:
flag = np.all(test>0)
flag

False

In [53]:
if flag==True:
    L = cholesky(E)
    print(L)
    F = L.dot(L.T)
else:
    print('E not positive definite')

E not positive definite


In [33]:
def create_matrix_positive_definite(m, n, start, end):
    E = None
    flag = False
    while flag == False:
        E =  create_matrix_random(m, n, start, end)
        for i in range(E.shape[0]):
            for j in range(i):
                E[j][i] = E[i][j]
        test = np.linalg.eigvalsh(E)
        flag = np.all(test>0)
    return E

In [34]:
E = create_matrix_positive_definite(3, 3, 3, 9)
E

array([[ 8,  6,  6],
       [ 6,  8,  7],
       [ 6,  7, 10]])

In [35]:
L = cholesky(E)
print(L)

[[2.82842712 0.         0.        ]
 [2.12132034 1.87082869 0.        ]
 [2.12132034 1.33630621 1.92724822]]


In [36]:
F = L.dot(L.T)
print(F)

[[ 8.  6.  6.]
 [ 6.  8.  7.]
 [ 6.  7. 10.]]
