# Ex1: Decomposition

## Câu 1: LU Decomposition
- Tạo ma trận A(4x4) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
- Phân tích thành các thành phần P, L, U. In kết quả
- Tại tạo ma trận B từ các thành phần P, L, U. 

## Câu 2: Hãy dùng LU Decompostion để làm lại bài toán này:
- Cho: <br/>
    2a + b  + c = 4<br/> 
     a + 3b + 2c = 5<br/>
     a          = 6<br/>   
- Quy về Ax = B. Sau đó giải tìm x
- Phân tích thành các thành phần P, L, U từ A. In kết quả
- Tại tạo ma trận A từ các thành phần P, L, U với tên là A_new

## Câu 3: QR Decomposition
- Tạo ma trận C(4x5) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
- Phân tích thành các thành phần Q, R. In kết quả
- Tái tạo ma trận D từ các thành phần Q, R. 

## Câu 4: Cholesky Decomposition
- Tạo ma trận E(3x3) vuông chứa các giá trị ngẫu nhiên trong khoảng 3 - 9.
- Từ đó chuyển E thành ma trận vuông đối xứng theo tam giác dưới dường chéo chính
- Kiểm tra nếu mọi thành phần đều không âm thì:
    - Phân tích thành L. In kết quả
    - Tái tạo ma trận F từ các thành phần L.L.T 
- Ngược lại thì thông báo E có thành phần âm
- Chú ý: dùng np.linalg.eigvalsh(E) để kiểm tra xem mọi thành phần có âm hay không
- Mở rộng: Thực hiện việc tạo ma trận vuông đối xứng với mọi thành phần đều không âm và phân tích.

## Câu 1: LU Decomposition (Gợi ý)

In [1]:
from lib import *
import numpy
import scipy
from scipy.linalg import lu

In [2]:
A = create_matrix_random(4, 4, 1, 10)
A

array([[ 6,  6, 10,  2],
       [ 8,  6,  7,  8],
       [ 3,  7,  9,  6],
       [ 9,  6,  5,  1]])

In [3]:
P, L, U = lu(A)

In [4]:
P

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [5]:
L

array([[1.        , 0.        , 0.        , 0.        ],
       [0.33333333, 1.        , 0.        , 0.        ],
       [0.66666667, 0.4       , 1.        , 0.        ],
       [0.88888889, 0.13333333, 0.42261905, 1.        ]])

In [6]:
U

array([[ 9.        ,  6.        ,  5.        ,  1.        ],
       [ 0.        ,  5.        ,  7.33333333,  5.66666667],
       [ 0.        ,  0.        ,  3.73333333, -0.93333333],
       [ 0.        ,  0.        ,  0.        ,  6.75      ]])

In [7]:
B = P.dot(L).dot(U)
B

array([[ 6.,  6., 10.,  2.],
       [ 8.,  6.,  7.,  8.],
       [ 3.,  7.,  9.,  6.],
       [ 9.,  6.,  5.,  1.]])

## Câu 2: Hãy dùng LU Decompostion để làm lại bài toán này:
- Cho: <br/>
    2a + b  + c = 4<br/> 
     a + 3b + 2c = 5<br/>
     a          = 6<br/>   
- Quy về Ax = B. Sau đó giải tìm x
- Phân tích thành các thành phần P, L, U từ A. In kết quả
- Tại tạo ma trận A từ các thành phần P, L, U với tên là A_new

In [8]:
import scipy.linalg as linalg 

In [9]:
# define matrix A using Numpy arrays 
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 

In [10]:
# define matrix B 
B = np.array([4, 5, 6]) 

In [18]:
# With LU = A
LU = linalg.lu_factor(A) 
LU

(array([[ 2. ,  1. ,  1. ],
        [ 0.5,  2.5,  1.5],
        [ 0.5, -0.2, -0.2]]),
 array([0, 1, 2], dtype=int32))

In [12]:
#solve given LU and B 
x = linalg.lu_solve(LU, B) 
print("Solutions(a, b, c):\n",x) 

Solutions(a, b, c):
 [  6.  15. -23.]


In [13]:
P, L, U = scipy.linalg.lu(A) 

In [14]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -0.2,  1. ]])

In [16]:
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  1.5],
       [ 0. ,  0. , -0.2]])

In [17]:
A_new = P.dot(L).dot(U)
A_new

array([[ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  3.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00, -2.77555756e-17,  2.77555756e-17]])

## Câu 3: QR Decomposition (Gợi ý)
- Tạo ma trận C(4x5) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
- Phân tích thành các thành phần Q, R. In kết quả
- Tái tạo ma trận D từ các thành phần Q, R. 

In [18]:
from numpy.linalg import qr

In [19]:
B = create_matrix_random(4, 5, 5, 10)
B

array([[ 7,  6,  5, 10, 10],
       [ 7,  9,  9,  7, 11],
       [ 8,  9, 10,  7, 10],
       [ 5, 11,  7,  5,  7]])

In [20]:
Q, R = qr(B, 'complete')

In [21]:
Q

array([[-0.5118907 ,  0.48082372,  0.71157749, -0.02083107],
       [-0.5118907 , -0.05651115, -0.35292388, -0.78116524],
       [-0.58501794,  0.1657022 , -0.51512972,  0.60410112],
       [-0.36563621, -0.85916111,  0.3220925 ,  0.15623305]])

In [22]:
R

array([[-13.67479433, -16.96552024, -15.57610263, -14.62544848,
        -19.15933751],
       [  0.        ,  -5.58311051,  -2.46158758,   1.27676897,
         -0.17049128],
       [  0.        ,   0.        ,  -2.5150772 ,   2.6498622 ,
          0.3369625 ],
       [  0.        ,   0.        ,   0.        ,  -0.66659434,
         -1.66648585]])

In [23]:
C = Q.dot(R)

In [24]:
C

array([[ 7.,  6.,  5., 10., 10.],
       [ 7.,  9.,  9.,  7., 11.],
       [ 8.,  9., 10.,  7., 10.],
       [ 5., 11.,  7.,  5.,  7.]])

## Câu 4: Cholesky Decomposition (Gợi ý)
- Tạo ma trận E(3x3) vuông chứa các giá trị ngẫu nhiên trong khoảng 3 - 9.
- Từ đó chuyển E thành ma trận vuông đối xứng theo tam giác dưới dường chéo chính
- Kiểm tra nếu mọi thành phần đều không âm thì:
    - Phân tích thành L. In kết quả
    - Tái tạo ma trận F từ các thành phần L.L.T 
- Ngược lại thì thông báo E có thành phần âm
- Chú ý: dùng np.linalg.eigvalsh(E) để kiểm tra xem mọi thành phần có âm hay không
- Mở rộng: Thực hiện việc tạo ma trận vuông đối xứng với mọi thành phần đều không âm và phân tích.

In [25]:
from numpy.linalg import cholesky

In [26]:
E = create_matrix_random(3, 3, 3, 9)
E

array([[ 5,  5,  3],
       [ 8, 10,  4],
       [ 7,  7,  4]])

In [27]:
E.shape

(3, 3)

In [28]:
for i in range(E.shape[0]):
    for j in range(i):
        E[j][i] = E[i][j]
E

array([[ 5,  8,  7],
       [ 8, 10,  7],
       [ 7,  7,  4]])

In [29]:
# Chú ý: Có 1 thành phần bị âm nên sẽ không tạo được L.
# Kiểm tra mọi thành phần đều dương thì tạo L

In [30]:
test = np.linalg.eigvalsh(E)
test

array([-2.54176053,  0.12861241, 21.41314812])

In [31]:
flag = np.all(test>0)

In [32]:
if flag==True:
    L = cholesky(E)
    print(L)
    F = L.dot(L.T)
else:
    print('E not positive definite')

E not positive definite


In [33]:
def create_matrix_positive_definite(m, n, start, end):
    E = None
    flag = False
    while flag == False:
        E =  create_matrix_random(m, n, start, end)
        for i in range(E.shape[0]):
            for j in range(i):
                E[j][i] = E[i][j]
        test = np.linalg.eigvalsh(E)
        flag = np.all(test>0)
    return E

In [34]:
E = create_matrix_positive_definite(3, 3, 3, 9)
E

array([[7, 4, 6],
       [4, 6, 3],
       [6, 3, 9]])

In [35]:
L = cholesky(E)
print(L)

[[ 2.64575131  0.          0.        ]
 [ 1.51185789  1.92724822  0.        ]
 [ 2.26778684 -0.22237479  1.95133091]]


In [36]:
F = L.dot(L.T)
print(F)

[[7. 4. 6.]
 [4. 6. 3.]
 [6. 3. 9.]]
