# Ex1: Tính toán 
- Tạo một ma trận A(3000, 3) có các giá trị ngẫu nhiên từ 1 đến 255
- Áp dụng tính toán PCA
- Trực quan hóa kết quả

In [1]:
import numpy as np

In [2]:
A = np.random.randint(1,256,(5,3))
A.shape

(5, 3)

In [3]:
A

array([[136,  50, 238],
       [  5, 235,  73],
       [245, 123,  25],
       [119,  89,   4],
       [ 80, 230,  62]])

In [8]:
# colmns' means
M = np.mean(A.T,axis=1)
M

array([117. , 145.4,  80.4])

In [9]:
M1 = np.mean(A,axis=0)
M1

array([117. , 145.4,  80.4])

In [10]:
# center columns by subtracting column means
C = A - M


In [13]:
# calculate covariance matrix of centered matrix
V = np.cov(C.T)

In [14]:
V

array([[ 7665.5, -4489.5,  -685. ],
       [-4489.5,  6992.3, -2926.2],
       [ -685. , -2926.2,  8534.3]])

In [15]:
# factorize covariance matrix
values, vectors = np.linalg.eig(V)
values

array([ 1782.95098565, 12508.27132669,  8900.87768766])

In [16]:
vectors

array([[ 0.59036423,  0.58757509, -0.55337653],
       [ 0.71699371, -0.69662239,  0.02524407],
       [ 0.3706617 ,  0.41167069,  0.83254859]])

In [ ]:
# project data
P = vectors.T.dot(C.T)
print(P.T)                                                            

[[  82.53329189   25.00780233  -91.24436688]
 [  52.0166929   -66.57059016 -119.8474299 ]
 [ -90.60078064   86.08748836  -20.62662914]
 ...
 [  51.79830577   76.05593073   87.23378085]
 [-157.89894885  -19.03052199   37.41784049]
 [  80.55561364 -134.82208907  -70.64110002]]


In [ ]:
P = C.dot(vectors)
print(P)                                                            

[[  82.53329189   25.00780233  -91.24436688]
 [  52.0166929   -66.57059016 -119.8474299 ]
 [ -90.60078064   86.08748836  -20.62662914]
 ...
 [  51.79830577   76.05593073   87.23378085]
 [-157.89894885  -19.03052199   37.41784049]
 [  80.55561364 -134.82208907  -70.64110002]]
